In [1]:
import random

In [2]:
random.randint(-90, 90)

69

In [3]:
random.random()

0.40283430362410977

In [4]:
random_number = random.randint(-90,89) + random.random()
random_number

-68.78589189023876

In [10]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90,89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [11]:
latitudes

[59.14560254222545,
 -58.10008962030758,
 83.13523507615312,
 22.8660700371734,
 59.50390939803902,
 63.414890065706565,
 -57.22132923202967,
 66.44666605782264,
 -69.78708169558422,
 -35.697219692060195]

In [12]:
random.randrange(-90, 90, step=1)

66

In [13]:
random.randrange(-90, 90, step=3)

30

In [14]:
random.uniform(-90,90)

-71.19741047194896

In [15]:
import numpy as np

In [16]:
np.random.uniform(-90.000, 90.000)

40.200269013058374

In [17]:
np.random.uniform(low=-90, high=90)

-31.037328860983017

In [20]:
np.random.uniform(-90, 90, size=50)

array([ -0.11845574, -36.90632509,  63.12549407, -67.2782783 ,
        34.41912344,  64.1000954 ,  11.01836223,  45.80282179,
        -5.25159756,   2.07848145,  74.8388158 , -85.17254865,
        -1.50259243, -45.83569639,  86.59180701,  66.72910402,
       -36.20533292,  83.32984022, -44.56409436,  23.7467117 ,
        -5.98735751, -60.29699619, -37.12302152,  57.05269321,
       -74.00265973,  75.99035686,  21.45641951,  59.08096427,
       -54.77240625,  78.83573881,  -1.59351197, -14.89775546,
       -41.52820699,  10.63532711,  -4.84183597, -11.93600168,
        19.28525971,  -2.03571373, -66.16170848,  59.70564129,
       -28.77191372, -45.63336749,  42.01782094,  60.78149646,
       -57.22037011,  -6.88404238,  10.79612325,  83.09168506,
        71.3327959 , -30.30724984])

In [21]:
import timeit

In [22]:
%timeit np.random.uniform(-90, 90, size = 1500)

12.9 µs ± 585 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes

%timeit latitudes(1500)

1.69 ms ± 57.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [47]:
for x in range(0,1500):
    random_lat = np.random.uniform(-90, 90, size = 1500)
random_lat

array([-38.08732747,  38.39442943, -14.16031688, ..., -10.12236906,
        87.14530678,  36.5589407 ])

In [50]:
for x in range(0,1500):
    random_lat = np.random.uniform(-90, 90, size = x)
random_lat

array([ 66.56277226,  71.38020304, -41.88338844, ...,  42.29844786,
       -79.76950924,   5.25602851])

In [51]:
x = 1500
random_lat = np.random.uniform(-90, 90, size = x)
random_lat

array([ 44.67957703,   9.22627177, -14.50673483, ...,  65.72095709,
       -51.04339524,  88.81530808])